version: "3.9"

services:
  migrate-manager:
    build:
      context: .
      dockerfile: ./docker/migrate-manager/Dockerfile
    volumes:
      - ./examples/migrate-manager/migrate-manager.yml:/usr/migrate-manager/migrate-manager.yml
      - ./examples/migrate-manager/migrations:/usr/migrate-manager/migrations
      - ./examples/migrate-manager/migrate-manager:/usr/migrate-manager/migrate-manager
      - ./dist:/usr/local/lib/node_modules/@thequinndev/migrate-manager/dist
      - ./bin/migrate-manager.cjs:/usr/local/lib/node_modules/@thequinndev/migrate-manager/bin/migrate-manager.cjs
