version: "3.9"

services:
  migrate-manager:
    build:
      context: .
      dockerfile: ./docker/migrate-manager/Dockerfile
    volumes:
      - ./examples/migrate-manager/docolate-migrate.yml:/usr/migrate-manager/docolate-migrate.yml
      - ./examples/migrate-manager/migrations:/usr/migrate-manager/migrations
      - ./examples/migrate-manager/docolate-migrate:/usr/migrate-manager/docolate-migrate
      - ./dist:/usr/local/lib/node_modules/@thequinndev/docolate/dist
      - ./bin/docolate-migrate.cjs:/usr/local/lib/node_modules/@thequinndev/docolate/bin/docolate-migrate.cjs
